apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: ghegde-cicd
spec:
  encryptedData:
    webhook-secret-key: AgByjeFcHHh2XKaWgbgiLqmh6pDxLt5esRkzmMDu9L4D5tI8dNhF3HQnfAD8/LQPIBojbQq/TfydpApXxgXXhZpITlUoijbDkT7eL5JPfOk9Ev8FLPTlKmln/i2yU1h5Xudq3xHWRZrc48vBUyhNy2gxgHslTTCQD04hebWAwHRf3iiD6UdM0NMp9V1cIilaXDvGqX25E5HFjFUFRu3zS70YmXOEpD7biavDH8AE9lKpGuKPGHqb8Sef+PofcqgTEbwooAcw3g3GjIbae/8aQuWQOz/Ver6QzzhQ/FsPkLKjSwspwAkvFa3+GcB/cTy8mP+9LQrXdu5A9yQDdeSDJFIv2RmTv6i1dogBkWjKbP7mCaMjkFJoLSpxnjxJOWwreDxB7F8QFdekGLtSiQG+Mr4a/IQF09OAlrLzWhf7RI0GuGYrHx2f2UoIdAs9PW1bxkaOsHD3j5rgSSQqLj9TTi7e8y2G7+K3Aa5IACVrx0JqUX0sxH06yOZUjYe0GqBflMYhSDAakCbKcfd8Qt3HPxDKHMGY5+7Pxtr9UeGKiSwv1/0jsqZYFX1+bmKpHYHhrdRnAfnxYYeZoTabZwNSkk6VUz/F/3oCnKAHsRLOa/I0ZLBf2ZuIS7w31zzhBK2rHqyINEjX41LCCShQacnLaH1mrC3JeW8wgMMbOsJX+Bvd1YuKzcPxueVnOnXO1bsBdMPwbVgZj6x3jF8HL0JDIa80VcgtLg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: ghegde-cicd
    type: Opaque
