apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCOuvPgWs2Japn/6IRbuSQES+wuBA1CGKGU8fEGJOETAxH7MhY8Ttl8ZkC8atLzNHWgzdAjbZZrm8AJgNZKDtYd/PCuwsvJ8iDCUMSkUBguaDKq1bVwnse3MMsBrMTNWF1q96WRFUXxN6826o4dxIg1EBXpb/iMMb31h+jmTOs1zlwIooDuw3/bCYJ/rWAGRcEAAyqYhx+iH3d6bIcerr7pqnP9FNNwmOAjpAN1MuJK1vRo58Rp2mZ/9HHLGPPsaU6yCb9avNqce+ZV/p5mTwA2ADCsHudI9CwMbHvOdP1oLjHke4UsWYchVTQca8lUdS0l8GOGKk6Q2BHq9xj4ub3dzieNFEX8VwI2Q3mZn8WXm2ckiQL7Jffa2ESZelCTZlZMAzHOPSK0JQc5WIJm/qh8Y2qPyBBsgPxue7zvoXpXV1szvFB9P7E7B58SWeQEZdv+jU0dDdJIevqx+V4Vb2KSacrzc6O6kDMG4xeIdbYaEx0zinUigWLbFEvTOarjyueu9QncaB7edLc6j7ZLlVV02U7DbAgbvoUcdmdPRGwvNoN0o8OBwP7sjX3xaH2/BLUCcrc6H6qY8o6TvcEXHZduGi1hHWASOx8X9B6+a0Z2KgR+PaAgqLmkcXrwwihksYLYkXhHv6tzoCFjE2HtVFV5ghuD7dORmYdHuG3i90232hksPsw6yGxhww9ZBwB7mcOoMupMmFhsDnV/nWUfEs59x4aX+Mz7QizVPmKUYQySH7hoOie+PNoLmpt08gtcG6KLFEUqflciPvUIYpotY1JBKkLD3lpGq/+ek7Kl6jPlrZSEMR2SyfiGrInxv3uF78hqlitiBmOwprretBbnLhBDzzGU1KSaV0r6mcqhbub64ZsmU2q99aqgaCzcLcR3qDwTInSgrNetsn5cWRoqfSYF5FZUkQjqQcOFKxgF9YXPx/IUcvO6wnU=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
