apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCCVIvy8xhotu7tyKkXxzJJAuwKbcMet6IFn+4AEO3bWJ9Gx5lSM0WKpV/5wNq58XqjvtVs5P9fSq5210nFXgRpcxtR7Ghga3+35Ir4YeyXFfWRn1x5jIb/9MiAr2Tlxs1ptFOqnHFe/ULHJTDiV3CcJ9k/lvADWqnsO6Dxw2BExzh57X6QL8DxGT/aI5TU1h5d0SE0tfFAkHo/3gBvXBy5mwU0NRUkzPfwM9FGnr59fcfZTLLM24NjCXC214TjW6KmSwksgRc0isRfTX/aDwiwtU+CdOWk4lBC60gcAhRXorgpJSlvDlQv69MTYJjhmlD+t6mFTX28Gg/yjWGS2JbvUlOBtcIxxw7viNLkZ1nrwyMQaWxCGO4Jlqq+FTxqK0pnus5YHcuOeu4H0M1vT+344dsLLpTu9ISCIfeZeWhzYDxn3jJ3ntYGQCuI412LklTzhzNz038DEy96IIZZ5F9/waTkxau1P3RjKl/P0PfC/L+uvV4NFvpgvCv3n+P9if0qNILpJ+DXV3iLlMOR8mvD3mSi3QVO+wQ45OIQq4KtVrCVNVGFE8mUmqeUp2afabklugATNIeykC9E+08UUNweS6kbuRKXV6rGAQ4KAaMIYWg8514Gc9k97oGg32m97tY7fJ7g+U1EQSM4OjD0mF7mENMPKwl5Di3J8uHvgFqk2MfeZMHd36txBvEIRNtHBqVggNDEJ3A=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
