apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAyubpX1zKx5ScdXxkCDbexpdKEfIQQUyfvXEeEioPMT5/eE/YHbG9J/p/kjKcKfH82beGZapm0BA3eWi3WtfawivxhojMbURVU9dilO2y46aFwPuWCqoyCFHBER+teJmDuB8UA8OalnUwgzhQWeDR2eAMyYwHSIvLVaidT8YCv6x55ODDHfpXz8Spom+Inap7Yt9CtmmXdFq3XXEyzQba0PSq64y9psnCYM+nWNDVhsOHTu4bUld+SAQKoNEtDd8LsuFV6urJn4chbSy3QOhfNhiHheStCRGqRWdSfND+oZQyK7us6zznDvfOzYM1IAFHYIZQ5Of/LdQECxg1vgKmtcKTL6ov2CX6qoSnQEjj6ifL+GC9UwWa7VXkh5WmMQWl6PQop1pzhaqx1IsQXhbnDnIOYyuM0PIwXTU81fP9EZsT/uNe1YPk62Ce6y5K6dQ+BvcAo0SSgToxl1Xy/NC9f00VIBdskt0jOUfYcX4OkenSfZLVaUPzGMusROwjFiXWar9QLe1v9YKWIPO3daazFhhiWayj7R0/ZJwxjV9YueCgGKdvVaiJ4Djkei6KyKxfe5PR9MABJqrLne8VUeYfQyfLqUmrK/kcXX/D48xLju1zbqRQOsOlCan+cGtez+QX+0A+oBBSiilcpbWMjg+MnpPj+mc3QNdxHfmcpgrp9nMSCivaeqnUt4hKRFW8Q9STnpkgt5ps=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
