apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDR434H3cDr/bRAk620+gphO6SCiopkVQ/YTcgUQj/tQHdsV0hOobWyG7RAUPLNGBalb33jza3PgqFP0qNfujZtB/KFHV5Y2VyjtYvE33KWWUMeVdjgck/sUuhFL9J9LgF6ytOXkLTrDxh7v30dfBTSa2BUXvCRLVnhxRsXpF5LCy2UCqc1WEoyzBL8kWcJSoFX4enu0cVXZRct9hJehH3z7SEqyIKBU1NiZC0pMxTq6huU9X/4RB4SG3C1EkEGoyGdpLdJSSrjBerhpwIJ1i3S1QfyQ5SNDmlfAxj/9r82WjopYE2czXQps7qCFVbRMNUH84pZT7B46PNBnhTNz8Ggw9mN8YsuyGZOhS60cUKtPFCRvYrdzu8QakruXbpWiEPpdF9zTA+bsHQ1fesrEBak3Z/knJ03DM/0yMQ3xFFZKZyIhp2IWnzQf0F8xokjvE0QnLFcj3mJFGLuw0HU3Ec0PMmz7BKkVWJFjwWj6RHjlu2YJuh6TDjTKq7VPBP45e0pTnl9blvcn7YAjtp33+mMDzDygOsHA2zGxqhp6AdPSL3q2sAhCvLAWRTDzqcOIId3xv+WDv7lP+mu3/OS8YpU83J+4Wx6iwHtUOH/n6b4B1egIntD8CjMZKiR1IrtbCGNs1F+jobW/CAHzGCG708IVFJqSn3NLYsILASxsF45qU5LvODuifEWrwsA+tvGLxwJSX50LuA=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
