apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA/aGGHF8oMRtHOMCNtsIIdNuviewV3gwXWSzC9BRg00mkNVHOJQ+FluTra4yAEqufcssRpGkt+OiADVfyPaC+BUVBxoNwnqmHG3pPEGcX/k+cevlNS3HYGSRuZCJ8eVgoZHsOSKyzirU22QgkvZNKOYBoDehGaYoxnzFjKzonm3VMlUKMXuiLXRFdv7KTUmaJr9rp36BjrwLl2CfxY58NxCrPkZoS9LFO08n84OkdKp061XOTNx2RYoD2uyDxtCR4nudWK89GGGqyEvC69Woh7Nn9T1mgvQa31imS1MqthbJvVu2IhA7muUsxZUyU1rYaYreTmLgBcmX9OiMMYeL6iZVnfRzVAGxsMtos6azdcYibok/OMy3MI1unczDyyZqm1lrUu+mraBi7vcsA61COKn4O2CMUGCNoI7yhEJyNbni+MoFrOLoMw0PO4XUZYfXTD2RD+M9P9fS4E+Ds+5OEo4Zqzbuo6Vlc+otH3UWLBFP/Oxas+ffYPNq5IWldlX+cI2+ZCGqPFlkXz8pE1t++ze8ZRMXqohbHJ3c1AdrPSdyL8scr7eBiglBG3FQVE9bRcRwzIm57aGQhTmHIARQCJRIkxnaLQOsErbhcx/ClK1PAig8/5qagx4EboSZlAPg+eWh6x9FQRW/cDdR/iswjDurs7QuSqR+4f8Foiyb9TED/NDgev0Rgo/OTZBKmHtIn4X4H59mQ=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
