apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCiAxoAP4J4BxbYlC5ZqSCvgKF0gaZr+41WRq6bORHCCZhSH/Yj7+7Sy+ezJJ5ILfoW+wVX0fTTAI+5qV/TX9W0caYkqdRtKM1oIYbi2eX1zZsCYSIIK523rCOKgbYPkjHo6dGxVAharA0jKjJIq9iZP6WWEnqwdiwA+YwdXuRg0I1AOm5LObEXZDYcEusB0jQBaNFsfYK6lPLW8WUUjhwzjrg769q+AqRTUSj/sEt1nTnotWyCihc6hd5Kfs8vF2V4ICnAQ7YqVXmAwGFe646nY+Sjt3gZCzOvMptiQAVdYj7+o5gA2JQiFYxBGfUgiQMH8hIBfZ31EQFIWz3nqh2fHX3d4AlcTUWf/VBEhslvxFTwe7TbIF05EFrYhDNSdujAFVf/3ygbPooe++vI/V3tUWGLCqlRcbYXeHFMR4iv122tht53wvzTM65UZRJy2bljrwcQYQMY+jMIHngLyNDUc35lXjAqPWUaPnUJNl+ssoflNleDj5qH1jXWottOsvVY/CMJLaFHes1U9jWpKNAPcjENpsCn36t2wCJLAxpOrHlL9nZ8qr8g0dKHbICweQqUKfA0sYhDjsmh6I5D34JW1nmLLj0NmGYXBdGoZjy1Ig3lx+osneLzrIQ2K503CAuehc/V1yJQ7AtoJ36/3wSUz+pPcSqjG/VcuRZTSIiV1UCIRuztJfsw/qTj2ZPO8NIX+ZwJwq8=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
