apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-gagan3-prod-go-svc
  namespace: gagan3-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBtJOQ2Rn+GNclmdXHY6qxbNLdMMKA6Y4IHP7wD6tkDgKe2B+t3HQkqH6Dqs+ncol+HiIcUaApQvK2/YSaRoBACWAvwfeVpgLwHSS5W9zglgDbTreZNDQUIeefPedm8cTqUgMqEEY3ceXhXLE3HFg1onqLJasoqt0EeEI/Y1rF87tMOttD4O+PyWDIUqUPaPjUsis3f5jdEfny2jxXxHXMrKX7dBqABvgt3KQN9je+Xr2+ETmu3BdwPMTqRhXkdrYbtJ61e4crDHwj+XOQnZru+EcVJVRMJhk4WksHVP3yxt6S3mkniEwm1h5g2qkKQ7dmlts8+T/BpIgzJzz3XJ5PG5x/GqjJbJy6ci3ZappOJUa3kE0Crh1uGoAmMY4LzVK0dEO1DJK4vlYGu51uc4U3k/fGJxnM4suRVAL+TxHebJPrYp6Pb80N8vk7snZ7B75PwmjlcK/gKJJgkVo12i/JXkzTbMxxOPIp6d398u5WJSbGtOrdAidr69XXim6kmEkI9hA1pgR+TbRtzHoLQ+pMrROM/NFrg7HrLPAovyqG8PS5LLx4YxRZ+3PoROY+ErNPIfltdc0kuUixTXFD/9QsLfJ7QnTMxGmZL7rKF55n6P5XxK6ygwZB2Yc1FdCpYsfTKa7QOodJR8rIUGdN73/mHsglSb8PXKM13vR4cnspXLuH8wc5bpAsPMXmYi/yKz5xXe4zo1Pw=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-gagan3-prod-go-svc
      namespace: gagan3-cicd
    type: Opaque
status: {}
