apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgA0Bc0pYPyk77bMhW4fHWiTvL7X0vrkMP64nKKSVWb7DI/CpwjYkhRTnJEMK8LssF05HIN0E4qrRc+BFAwhM2p3T6gttRiwgyw/giHScw1/sLpzJ8tcg1KrqRKkSYiGK6wt1uHOZQFo5u3/4CDrrQ7v99mFehmIljyD4B15Mby7eAe4Jtk3ar4vxFqUhIf2GjgnH5XZGa4eDUx4zNt0+zK/zQ1VBpdqwdpWsoiJAAaNqxAiVbQQ2AAfugrUEpgcUXNZTIX6fng/WM/z6y8Zp3+/rEqOnFctVqFb3yYcyoGyMpEt2f9xJY3JCqLvVYX3bjuCXPyJH4cM3Vtx+dKVvaW1jCy5fPxFzjP40ZVSxQe5V3LVVE5WohOwkHFt5EBkF6wFXpBHW6lu552kIdxSOG4N0BvWWSyTfLwrrrWVtuNXRvdip0GVwRH7Pn5hIFb1o0vnYrpIhjbq03xsOi8tzR2kSiGSzpFdXygfWLccnlzBMQpDDoK6HWTof/h4woLwW5Mm/73WhKtqkBGwiFKZuwIN1bCxx52yn1MjiOL6kOwsU7TONqJqOmsFyGwQpWvR7lm+pGNpFIOxCwCH0vbYSbP5AIuNTHw8ToVjAT5AVINnIoEfkf9jv7AK8xCP3dbaPINe3X2gnzV9VCLhxjdcKVtcK74Hqpfn9FLeCPRz47Y7XDVmDB0sbHv5xqAkxmKtJPOgAerCj/YGLGW6WBOurBG2Rh9HjQuIX8uJzIGaB1MSCYdFXO8rO8+E
    username: AgBW26RzqFoCvbyCcul3mr9GEQRnymVFTvA6Kes0KwNvBkVQlLfNOrGV6QmMP7Ei/wKzR9wnW1MPvOUopNYnPN8u6lfZOXJ6uk2UKuIz+dTR6oLWkDO1sZoSVlzFOy/51exowHJxFGyQBGt81UQLnN3/v+CIa1g17hjEivrR12p96M1n6/TzkV6vdxgqddU+Pz6PJNY0NmXSqUJIELvianiajZDeMvGLTmp2xWW6aGirn1CbJJVPhqm7Dadeb7fjgtrnFPhh5CgboWXsrcHbFLlpX1gfLHKNgPvZASV97KqPG25ld4WYnHcPPUBgUC0NHKhoS3Q/xZxlcMZjAo6h9PDBpySLBuHiBAs38B49St6vHjsbqB0W6zIt72DytcDnmF+bDdJND2cDQ62wpFGwZvGTNLztnjf5yabjG34NIjY7agv7FK33I1hJTaIEAyoSQW2StJerInyyetqwMZaVX8XE4WnL+mfXqRmcl0aLYmMO8W6btIUuPXmGL7ZcHA6I6IucFhLtb3avr+6jbD3YE+VRHCMZ4seQb//njxAA2wc0ljC1ziQMqdcQRqy5hsIflOnjiGyPQ9x6Cuc/FQhZeckq9ep4h1ZWwz8bOlnmmIR6frKhWq6Us9Ysv5hZyR5/9RZbswKyQFF+MWiy6PoANkxCaf64J6EygZ7iki90mYliXwvYwva9d41IRPxnMuWCHbvNWQ8Wc6I=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
