apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB+WiERhQ5h2Y+bTQK1srxnw7YCzELMxFMmLGzxq0pXPPy7ITWyDKlAZPEoSq5r/JFAu2bEVBwi6kyhdaGuc2lvh7Ytm4YKddxgUaWZGMgwsLixpJ/MMWz1tsNO0/h/PrhDQskm36CHleG9k4UGEHpw4V+ngwv438a4w+DSVqPv9bfd6Q92ud0Fw66fouZPsiVeusYEv7ps3lRfnoH9KML7/WRAr7xZikdjfKEKGlSrAtZL3yDT5xqirVwd44h2F20wXxv1jw+gR527eugn3Ti63zGKzL2iIJ0bsK2AzLriPsvQkwgXq310CPt0XnMoO5YWI6tStPT4U5bURKxx/Tps5Ru2ufmLU7hYb3E7yCGXGNdRQyuVByu627W+GwlttJr7prMp4bDZ6DRcPfkFs2dIafWjYO8owsEPErdvpBnXkP4pN8zVunYWbfxrKEfvTiS7qhBYppj1o9+/BeMANFZyLh8SPmdnQqyp93FLOHAhWMVZotOuhAqn7sOsm5Gwu4LQsAim7AOzUfYx1PHQ387DLv9mAV9eKQSCgQqP7EC4rTKBQW/5XWZ55UvWSkM5oeQnMHoncGbANhq+O1X69Fgy4K3aMVqubo7Zt+HcM1WvzStFpAiFVxyA9Vp8ArmATPgIdcPtH6zIFkkEkycL/edZYGWT52gq5GlOFDxn+SYgS8nuCx75V7GvFjJCsmfq9BLZHUQDhs/KSCbT07wRPCgQBnEqrg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
