apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAzPfe2e30M4L0oQaILFBHBUYWljrPW+AlWFmbDJ9eabaLrHYYSgt/uhfrGc/mnv9LGoLw/VU/g9NbQbglbCxX2Rr40+yDEznrpz4eG9dkU8eJPUqncOtkEe6N8M0PdebMFADMJNCzRPjJreOyDU1M5DsWdzQHXKbfa28Gi/H61cxlXusibbGRyMTAej+0nz9TjOZBwvciR/3ObtYyQSeG31QjC2IW6/9GT+2OQB6fix+n2mafQ7cpCPDKrxqje4y0CdjF3UCEwsQOH+FQcXl48LBvXgJjpXnjecgLXafYjQEwruBYSJgh0Vqe1xuluFRdGktryhpZ+dZC8cYvdgiHfJVtvNxfj9VLtg7eB1Ncoga+GGR6ZecnlkDuEaipMgLF7XZYy896yNlsZAUZzTc7zNQ7LArmQnYBQGJpwWrc0/mdcbuVcPuHxwFyGxFH5jyYVCwEGcq5CcCh1NCFll9bxPxpq6uzWWQyGgRXSIH2n3m3dKaYSNGH4YpsF0XhyKuiRtLuTXW0ZM7qlGDfeISx8dWDPqbLagiIhs2+BTAU28UH9+VKIpZNrEzN6yOTpOa7GAiJHj9WXVit5k11wf76AxBdvwnZL/QxcxX39G7iyaLfXzomIpVk8dQ6PlJlYKp+yKU8+OwgOobE6TxSFTMzUftNO7pLgH4hm5L0PKaz2hCfn+aOP7tMumWUMgtXGM+NfE7LuVMy6CKM6BZkqPj8nwgIuOQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
