apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAfHymjincJRdqmTMHzy2TzQQe8nCqsNf6yRPF6jO3x8McI2DG6ASKpQ5V3WD8LzKscNhBUah0GWszQtYZkqrc9BvKJLR1xEA4Ytwhs0tyNaPXaJcn/Zsin7iLLce8wbZGSF5hbQOgZ80LmdJPFukKTNV56SCZvKkGHhN5D74BSlzixRMZ6LOR/tGvxKvqr9z35Bl9FUD/PtRFJDbYBQM+e4FuybdfPVVKqnLVyy6WTr0SZmV0D32yVaJzjYl7wPko61VSzEcNKbVHdg5Xe+lPIsCEriHlRHsktW3fBPW2OpSuF5oYXwNOmKXmTKdkVCBVQVIQRV0j4iJMLM0CfxGtuSGnH2V7WLwxiXb97SzWm09nc6EXx4MihVR+mFBWA9G2DEb4WPSYM1uv/NlLB96zxbVI7O/IhqIPd+FdiGOh9UKeQWvs05sfYd8rOGdKrJAi3tE8I53MBfoVss9trNg/iWCgEjrH3VHC18ldaqhZj74KDVmkSCWndBAQtTQGDkVKkXFEcLsNvg7D2fHOnexGovJVIeEKs6pvAZR4wTWNTHPSpy3nOsbM5rTP7p9sRLUpG1pG8A4z9F+PoTy02eKpEgMcHDOfZSne+U0tulPC7ZNMWAUWww8bng0oaqbg59lLY+1TSWy+n+2gsFRZLZn0wcPF3bND5UcGixol+AaC8hbvTdqgA90LU/jLLQBoLMgK05F+tH17hE/vVRGWfLHQYbF5fMQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
