apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAKfvGrX9DkkXF+eryv0998GIgj4wdR0nvBjk9qaWErb4nQuQeIKsEp0s6DPgtiW9A/9jJDttx/v9sdCvir3OMcPr90/A6JzUkGq9JjSMflHZBLWoSqRtoqBjm+4maqUZuvH9FidLSOH3AlmPXKZ7Z7feESQ8j6Pfoh+r3rdHAOzFYTQ+SzY4nb5Sfu9xpI6JakAS5iUZzPk2cJXLAo6VqF3izw4yU30NdIl7HQ8Dfjs4kMv3vjgmr3TtXKsA9jKwiNUo+J0w+Zbixu0oFLoIgLk/9xMmGpmf+zCu2GNvL0aosv2iGCFaaaJAIH0AwuXIuQFLdM/FJnDFzo2DOnE+ZgOwpbnius143FGUiR8/Sdo0EJyyQo0zwy2MJYhYKtNwFt3z5qrIK8Xw/1rplE1WV2UlpOaFB6LnZhWPfTKgnvrwtTrL3GfgdAqLPT3+4i8/7Mo13BXeL+Xwb6fwH+2ImabZ6ewkJcuw4JuhQUSFBo+8hCGfeZ83lzvOTsSznxJJBKo0aKOJAzb2MaOGg8SvPC7XaE6qozjb5IwwdP/AbUf4jeGuRcweBs5z/otfcqzSJJ2LtHKruCoUjvlrmG7VeOaKaz8sXLdTbdXFHvbcOFSC5XvV4EnAKpXIrQEfKDRNTN12RoAf6Q6wC/80DAo8SlpF7IRn7iaro0kGMpr/gTx+mWbLcv4d7YkUcZYUQ4lkdiInBiDeDqe26iRXbv/wgCSVs4mQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
