apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: failure-dev-app-taxi
  namespace: endtrigger-argocd
spec:
  destination:
    namespace: failure-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/failure-dev/apps/app-taxi/base
    repoURL: https://github.com/gaganhegde/test-repo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
