apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBNcNCGDsooUgUKwbQToMDl3QtLZv0z/d/Kf4LBfak7X2f+9jaIYDs/l+ASuc9axnybULMlhxXw9Lj9jlI7OCyG/fOvRt0qWnxAjPkbgU5iF5e7h5P8rIzXDJNDHRC46G2HDQpx/PoipG1zjaluhXI4s1mKyQkW0WtfSBNztjdTWjsaxV+scVrg/QzRkpVtsA1bLIVY4yeECBg6XPt3uDXWvtPAqxhZdNpmUCRHOJOVSk7f2WxH7sMZUdOwDSObGiEpYDKmiGgEvNUA6KYyX8MA2dFo2QqvRnT4a71n0ktaMo7834vbghuvFw3+tgByDwyydlzA59lIlJvB3YpiW4KjGzCU6ppf7AsWxLLcQPou+FZpU/8O8e0rfmMkcNouqUwM8OYiRtC2YOgEXp155/NgHovbJl4pZ2xMtWXjfB/6vUnd/XXVFL052sjJmIbYXCxugeAo2GR8aXtFRCwc7ZLzagax+nFlFjqwJ7cjSdqPk0Ipbs9inokID1OFhOsHzWxAkO3FBPWYVWeZ+BClrbHeANP05lGITaU0QqX0aWpazwH4MLLkGw9guc6AjMX92cqcio/DuMevwJAm8FtnpCF7auhaoJ6JxosJ7kUsqQhgOw4he9OqNZnSEVHEx9A/Z5tAEUciH253WJykJGdQPbZyDRcqREuemWYjEGWMtE2PpdMbv2syfOo3TWYemztr8VeFD9XM86X7tPKMfwZGLV9agUIQsg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
