apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA5F2denazoB74FLTK4mcoE9cgdFWpHk6QkPFjwlMkh5fxw4N0uz3HJN0G3FkWfLUIBN5o6pMP4OVio7FOf/236Ciu6bRCtvq333423xlJVOp0nIuuEbbm2ZTcgNP7ugx9Y9dPF4W5yq6bECczKLuISt2XKKJ8OMup+04rb0LW21h9aoA8vOQ9hL+pKMRH/Sp0YCvz+E1dctuDreKVl6OT063v21+1Y8uXT7dib21MFA2lv4AqgD0IGAjtgrMVywMFRlARLrd+8eDgMH8NZ3K6zjyinwiY/zO4g7hOr8UYh5X6wkWgZSbcwNTs3VjW9+6x6g1lMzmVOok+KWupCaL47nuMSMjuJIXnw5EKatURmoRSgYWgUz6UTmbHSIQHjza5CQqthC6GdoU798eqJqRWylTRYDwmZHgmim+TpnIfYpTsZLMWDBR6XeoelTmGG3pt6+tzhmcEUtyapj/K7oqs+foeMXGoEEMqEfuOSnr57KHrEi26i89xRUe7tOGweB1HU0jn9piC/kgcqFq49Bu66xXCeWKNOuAcQCwo9O49oVF2S94+QwVysasCPe9tv9MKHcB59aJJZC/WfFzpsl0EOkDxIKdx6oflDBzL3wexazJV956vSd9QsNoTpAM45qwMwiaXRmys14bMW1ftI2dkru86bhjygMvz+4baHTs7Y/SudhXNwW+8Xxld5+lLa8mE7MGKF2UZLjgEOqSbiqAUvlkVGdQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
