apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: ghegde1-cicd
spec:
  encryptedData:
    webhook-secret-key: AgANW6d+qNm34W+OtvPm3wJtP6WdpZC1aW7J8PgHSYB/cx+YClILdST6nmiDFPNzSoXFNiXnb9W5hW80aTFM8t2K0TME9Q/YluEf8adY1SwMj8f6xO8KpsxIyVK8z9g/iPf1ZVVxKhkrOLdwOilE2qzJCxTB5BDw/WftQ0+dNUNHou1A3AYjZq1tveiNS9y0u3K56ZSvDyns2Nqw0aZINKu48eBjc00o1XLayiUUicJWbZJJB9D6lBPD/9jXt+zxMpZa1dx3TSqD1IahxRPMg7uq8W7y3bt1LyKvvc5vVzVvqGE0/kepaYqLgYbBJYD+YXogRTtfJxUrN7hLymYx3A9TXvSFLmcr6rUUc5qfWcMqqVVdYljJYNjFzAHLDWNYgFIIuMjb2p1xPnatT2Sog3KPa6bqTjDSKT5aDiisz/pW/lqP3Kz+/qAtBGR/4oZTWjjH/22hvDG3/qGJj3pCTZKY+UNT2c5gkDBaERP1u5vEnlsH5Z/cMhtRQbVsWS+QleSiTp3+BTLvWbrO9/HKU8P0U5QMFKXfCq/o/nQxheEjSsvwS+uEYZgbxPSRVmUcRsumJStBLpHn7EgT8hNEeElCNd6SFMBpmW6dfn+akZRGaYxKJwQanWO3nqx6wT8mXinps/ujX2Kks8OqZQauLqPekek4CeVFFdoH2N81E9FA3S76UuHQyDL0E8jYPRIimkdiX2+kGTZHBJaXOjkD9vK0MdPtDg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: ghegde1-cicd
    type: Opaque
status: {}
