apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-endtrigger-dev-taxi
  namespace: endtrigger-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAuZTSx7JtyDd4aO/8fr1eEzu5d3r59ZnigtjTsyO0mJFCb9e+8pYFvC04t9BV8nXC+zH+kXGVgRcsIvgpyJaU/sTIrVG5+c2QBgFMYYZ4u2zxUd22FGG1RC3moqryBX9s1/r95+qyUSNapMwDo9F3JbpC+ypISM52VyNzIgMOcphDir8kd+EZ8TCnCrZ+ivbbOXOXVuQq5yTt4jLP4QESvgQXnAlpDjm6aYyhce6IUvnIR4lYRr5jDTUoV5UbKK1PoGx3Wg/ydwelV1LCPW8m0kc9XNpUroqXI8EwlCDc1zR1iazfXwxDftKgwBtZOxd0wT7BDgYbnmunzCuOHCHLETAcSrHzCPL0Tz387wE/ZWtUe4A/94Dpc50AiSRP7drPCuVGlS4CD2G9V4x9lFtn6J200+8JDQFqBuSMuP5vY/GcB5qZnEC9dPbD5xBmjG5SDkoI6KqrMKMuM+s0LMSPDjFPazVw0P/y6Qt5S84+Q3UN2QPvjbJ/f5ZAd7HVI//+4bjV6e5CR1EUhf0wallt4JweKiEXKA1BVtKUt+6ecZgqUD6R/dP4jQCJESURTJGKWh2816yvpf9NFYRB2+a0qRhMQD4vsNhXz7MrbasqqSnuKqaw3SZtDtqcYEdr+cQUWtERap10M49I9yxjhXwi9OWF8EUxYMQtv2u2V7UJbaaU0YLMk/GrU5gGCxdDjaE6wZnaA/6deYOfSjBHXFGy/lp1iOw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-endtrigger-dev-taxi
      namespace: endtrigger-cicd
    type: Opaque
status: {}
