apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCyTrq+Cv+sKPHK6RqJrydZZpnzn9FqCiYulGEqkNImoZCODQRp3knwIceFg9ApdGnGahLrTkZuCNps2i9Fxk974L1tIBnzmys2/DLfXIO7tZF8aHdIcavTNC5O4u4vp4YwQ03hzGhMqpjk1CIzIeLoI6x5uzs2AmnGT/vMKBem5CSqt3UNCg7tYzJLpVO/iGV/Lq2+oGwpwrb6+/h+9BHfvAcpRm0N7ndviJwFDJ78y3CUUoY9GBjcpP5G0qK5OLEeUDeF/5Q+PIcfBiTmZcONja/DAavKl382YRuwNAalh3nqw3O5tQZXv/hNrG8wmvJiuUWCWK7TpEEIrxLnCJqvOPmPYZIZEzV4QwrrGjokGbb5CevwXZUmfwSxttJ++5+BfVwVQDztl8XVQfBcAFOapNfx/psx4ZafZr/KRVlludoLQUpsb2X5/8/n4yqgDKxgmNCh87raKSRC4uuux5jlStFXEzEtEkykX6ZyThSPeta0vFARzKdOfp8AhDd4L/5axscTV2KpDxmHiUTuDBXLT+HIxJIDngJ4Z1Z+MRPwvnQ2jINxO7Ueu3QsSObEFc89vJFVVmMpMQX8WAV7u9cB0mFsrrxuJ/meMqWjHBbGJWKhaXIt1qreqGVh6MNxtjw57zH6LWadNXyTkwghLErI6r74ZDXkZme1vaBHISDiqamLPzgdW6mwbBGwTVIt/ntJpKV8a0c=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
